# -*- coding: utf-8 -*-
"""Data_Nasional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tHjf2Wo0F78awEZtP3IbL57yPLHGzio
"""

!pip install pandas numpy matplotlib seaborn openpyxl scipy -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print("✓ Library berhasil diimport")

# Load dataset EBT (tahunan)
df_ebt = pd.read_csv('dataset_ebt_bulanan_cuaca.csv', decimal=',', thousands='.')

# Load data cuaca
df_radiasi = pd.read_csv('Radiasi_matahari.csv')
df_angin = pd.read_csv('Kecapatan_Angin.csv')
df_hujan = pd.read_csv('Curah_Hujan.csv')

print("=" * 80)
print("DATASET LOADED")
print("=" * 80)
print(f"\n1. EBT Dataset: {df_ebt.shape}")
display(df_ebt.head(10))

print(f"\n2. Radiasi Matahari: {df_radiasi.shape}")
display(df_radiasi)

print(f"\n3. Kecepatan Angin: {df_angin.shape}")
display(df_angin)

print(f"\n4. Curah Hujan: {df_hujan.shape}")
display(df_hujan)

print("\n" + "=" * 80)
print("INSPEKSI 10 BARIS PERTAMA DARI RAW CSV")
print("=" * 80)

# Membaca beberapa baris pertama dari file CSV sebagai teks
with open('dataset_ebt_bulanan_cuaca.csv', 'r') as f:
    for i, line in enumerate(f):
        print(line.strip())
        if i >= 9: # Menampilkan 10 baris
            break

print("\n" + "=" * 80)
print("MEMBACA CSV DENGAN KEMUNGKINAN DELIMITER DAN DECIMAL LAIN")
print("=" * 80)

# Coba baca ulang dengan delimiter yang berbeda atau decimal separator
# Misalnya, jika menggunakan semicolon sebagai delimiter dan koma sebagai decimal separator
try:
    df_ebt_recheck = pd.read_csv('dataset_ebt_bulanan_cuaca.csv', sep=';', decimal=',')
    print("✓ Berhasil membaca CSV dengan delimiter ';' dan decimal ','.")
    print(df_ebt_recheck.info())
    display(df_ebt_recheck.head())
except Exception as e:
    print(f"Gagal membaca dengan sep=';', decimal=',': {e}")

# Jika masih gagal, coba baca sebagai teks dan identifikasi masalahnya
print("\nJika langkah di atas gagal, periksa file secara manual untuk karakter aneh atau format yang tidak standar.")

print("\n" + "=" * 80)
print("INSPEKSI 10 BARIS PERTAMA DARI RAW CSV")
print("=" * 80)

# Membaca beberapa baris pertama dari file CSV sebagai teks
with open('dataset_ebt_bulanan_cuaca.csv', 'r') as f:
    for i, line in enumerate(f):
        print(line.strip())
        if i >= 9: # Menampilkan 10 baris
            break

print("\n" + "=" * 80)
print("MEMBACA CSV DENGAN KEMUNGKINAN DELIMITER DAN DECIMAL LAIN")
print("=" * 80)

# Coba baca ulang dengan delimiter yang berbeda atau decimal separator
# Misalnya, jika menggunakan semicolon sebagai delimiter dan koma sebagai decimal separator
try:
    df_ebt_recheck = pd.read_csv('dataset_ebt_bulanan_cuaca.csv', sep=';', decimal=',')
    print("✓ Berhasil membaca CSV dengan delimiter ';' dan decimal ','.")
    print(df_ebt_recheck.info())
    display(df_ebt_recheck.head())
except Exception as e:
    print(f"Gagal membaca dengan sep=';', decimal=',': {e}")

# Jika masih gagal, coba baca sebagai teks dan identifikasi masalahnya
print("\nJika langkah di atas gagal, periksa file secara manual untuk karakter aneh atau format yang tidak standar.")

print("=" * 80)
print("ANALISIS DISTRIBUSI DATA PER JENIS PLT")
print("=" * 80)

# Statistik per jenis PLT
stats_plt = df_ebt.groupby('Jenis_PLT').agg({
    'Nilai_EBT': ['count', 'mean', 'std', 'min', 'max', 'skew'],
    'Kapasitas_MW': ['mean', 'std']
}).round(2)

stats_plt.columns = ['_'.join(col) for col in stats_plt.columns]
display(stats_plt)

# Visualisasi distribusi
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Boxplot Nilai_EBT
df_ebt.boxplot(column='Nilai_EBT', by='Jenis_PLT', ax=axes[0, 0])
axes[0, 0].set_title('Distribusi Nilai EBT per Jenis PLT')
axes[0, 0].set_xlabel('Jenis PLT')
axes[0, 0].set_ylabel('Nilai EBT (GWh)')
plt.sca(axes[0, 0])
plt.xticks(rotation=45, ha='right')

# Histogram per jenis
for jenis in df_ebt['Jenis_PLT'].unique():
    data = df_ebt[df_ebt['Jenis_PLT'] == jenis]['Nilai_EBT']
    axes[0, 1].hist(data, alpha=0.5, label=jenis, bins=10)
axes[0, 1].set_title('Histogram Nilai EBT')
axes[0, 1].set_xlabel('Nilai EBT (GWh)')
axes[0, 1].legend()
axes[0, 1].grid(alpha=0.3)

# Q-Q plot untuk normalitas
for i, jenis in enumerate(df_ebt['Jenis_PLT'].unique()[:4]):
    data = df_ebt[df_ebt['Jenis_PLT'] == jenis]['Nilai_EBT'].dropna()
    if len(data) > 2:
        stats.probplot(data, dist="norm", plot=axes[1, 0] if i < 2 else axes[1, 1])

axes[1, 0].set_title('Q-Q Plot (Check Normalitas)')
axes[1, 1].set_title('Q-Q Plot (Check Normalitas)')

plt.tight_layout()
plt.show()

print("\n📊 ANALISIS SKEWNESS:")
for jenis in df_ebt['Jenis_PLT'].unique():
    data = df_ebt[df_ebt['Jenis_PLT'] == jenis]['Nilai_EBT'].dropna()
    skewness = stats.skew(data)
    print(f"  {jenis}: {skewness:.3f} {'(Normal)' if abs(skewness) < 0.5 else '⚠️ (Skewed)'}")

print("=" * 80)
print("CEK KEBUTUHAN LOG TRANSFORM")
print("=" * 80)

# Test normalitas dengan Shapiro-Wilk
print("\n1. UJI NORMALITAS (Shapiro-Wilk):")
print("   H0: Data berdistribusi normal")
print("   p-value > 0.05 = Normal\n")

transform_needed = {}

for jenis in df_ebt['Jenis_PLT'].unique():
    data = df_ebt[df_ebt['Jenis_PLT'] == jenis]['Nilai_EBT'].dropna()

    if len(data) >= 3:
        stat, p_value = stats.shapiro(data)
        skewness = stats.skew(data)

        # Keputusan transform
        need_transform = (p_value < 0.05) or (abs(skewness) > 1.0)
        transform_needed[jenis] = need_transform

        status = "⚠️ PERLU LOG TRANSFORM" if need_transform else "✓ TIDAK PERLU"
        print(f"  {jenis}:")
        print(f"    - p-value: {p_value:.4f}")
        print(f"    - Skewness: {skewness:.3f}")
        print(f"    - Status: {status}\n")

# Aplikasi log transform jika diperlukan
df_ebt_transformed = df_ebt.copy()

for jenis, need_transform in transform_needed.items():
    if need_transform:
        mask = df_ebt_transformed['Jenis_PLT'] == jenis
        # Log transform dengan shift untuk menghindari log(0)
        df_ebt_transformed.loc[mask, 'Nilai_EBT_Original'] = df_ebt_transformed.loc[mask, 'Nilai_EBT']
        df_ebt_transformed.loc[mask, 'Nilai_EBT'] = np.log1p(df_ebt_transformed.loc[mask, 'Nilai_EBT'])
        print(f"✓ Log transform diterapkan pada {jenis}")

print("\n2. DISTRIBUSI SETELAH TRANSFORM:")
display(df_ebt_transformed.groupby('Jenis_PLT')['Nilai_EBT'].describe())

print("=" * 80)
print("SIAPKAN DATA CUACA BULANAN")
print("=" * 80)

# Reshape data cuaca dari wide ke long format
bulan_cols = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
              'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']

# Radiasi Matahari
radiasi_long = df_radiasi.melt(id_vars=['YEAR'], value_vars=bulan_cols,
                                var_name='Bulan', value_name='Radiasi')
radiasi_long['Bulan_Num'] = radiasi_long['Bulan'].map({
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
})
radiasi_long = radiasi_long.rename(columns={'YEAR': 'Tahun'})

# Kecepatan Angin
angin_long = df_angin.melt(id_vars=['YEAR'], value_vars=bulan_cols,
                           var_name='Bulan', value_name='Kecepatan_Angin')
angin_long['Bulan_Num'] = angin_long['Bulan'].map({
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
})
angin_long = angin_long.rename(columns={'YEAR': 'Tahun'})

# Curah Hujan
hujan_long = df_hujan.melt(id_vars=['YEAR'], value_vars=bulan_cols,
                           var_name='Bulan', value_name='Curah_Hujan')
hujan_long['Bulan_Num'] = hujan_long['Bulan'].map({
    'JAN': 1, 'FEB': 2, 'MAR': 3, 'APR': 4, 'MAY': 5, 'JUN': 6,
    'JUL': 7, 'AUG': 8, 'SEP': 9, 'OCT': 10, 'NOV': 11, 'DEC': 12
})
hujan_long = hujan_long.rename(columns={'YEAR': 'Tahun'})

# Gabungkan semua data cuaca
df_cuaca = radiasi_long.merge(angin_long[['Tahun', 'Bulan_Num', 'Kecepatan_Angin']],
                               on=['Tahun', 'Bulan_Num'])
df_cuaca = df_cuaca.merge(hujan_long[['Tahun', 'Bulan_Num', 'Curah_Hujan']],
                          on=['Tahun', 'Bulan_Num'])

df_cuaca = df_cuaca[['Tahun', 'Bulan_Num', 'Bulan', 'Radiasi', 'Kecepatan_Angin', 'Curah_Hujan']]
df_cuaca = df_cuaca.sort_values(['Tahun', 'Bulan_Num']).reset_index(drop=True)

print(f"✓ Data cuaca bulanan siap: {df_cuaca.shape}")
display(df_cuaca.head(12))

# Visualisasi pola cuaca
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].plot(df_cuaca['Bulan_Num'], df_cuaca['Radiasi'], marker='o')
axes[0].set_title('Pola Radiasi Matahari Bulanan')
axes[0].set_xlabel('Bulan')
axes[0].set_ylabel('Radiasi (kWh/m²/day)')
axes[0].grid(alpha=0.3)

axes[1].plot(df_cuaca['Bulan_Num'], df_cuaca['Kecepatan_Angin'], marker='o', color='green')
axes[1].set_title('Pola Kecepatan Angin Bulanan')
axes[1].set_xlabel('Bulan')
axes[1].set_ylabel('Kecepatan Angin (m/s)')
axes[1].grid(alpha=0.3)

axes[2].bar(df_cuaca['Bulan_Num'], df_cuaca['Curah_Hujan'], color='blue', alpha=0.6)
axes[2].set_title('Pola Curah Hujan Bulanan')
axes[2].set_xlabel('Bulan')
axes[2].set_ylabel('Curah Hujan (mm)')
axes[2].grid(alpha=0.3)

plt.tight_layout()
plt.show()

print("=" * 80)
print("WEATHER DRIVEN DISAGREGATION - PECAH KE BULANAN")
print("=" * 80)

# Hitung proporsi bulanan untuk setiap variabel cuaca
# Asumsi df_cuaca sudah di-group by Tahun jika ada multiple tahun, atau total sum jika hanya 1 tahun.
# Berdasarkan kernel state, df_cuaca hanya memiliki data untuk satu tahun (2023), jadi sum langsung per kolom cuaca.

df_cuaca['Total_Radiasi_Tahun'] = df_cuaca.groupby('Tahun')['Radiasi'].transform('sum')
df_cuaca['Total_Kecepatan_Angin_Tahun'] = df_cuaca.groupby('Tahun')['Kecepatan_Angin'].transform('sum')
df_cuaca['Total_Curah_Hujan_Tahun'] = df_cuaca.groupby('Tahun')['Curah_Hujan'].transform('sum')

df_cuaca['Proporsi_Radiasi'] = df_cuaca['Radiasi'] / df_cuaca['Total_Radiasi_Tahun']
df_cuaca['Proporsi_Angin'] = df_cuaca['Kecepatan_Angin'] / df_cuaca['Total_Kecepatan_Angin_Tahun']
df_cuaca['Proporsi_Hujan'] = df_cuaca['Curah_Hujan'] / df_cuaca['Total_Curah_Hujan_Tahun']

# Mapping jenis PLT ke indikator cuaca
weather_mapping = {
    'PLTS': 'Proporsi_Radiasi',
    'PLTA': 'Proporsi_Hujan',
    'PLTMH': 'Proporsi_Hujan',
    'PLTM': 'Proporsi_Hujan',
    'PLTB': 'Proporsi_Angin',
    'PLT HYBRID': 'Proporsi_Hybrid' # Placeholder, will need custom logic if used
}

print("MAPPING JENIS PLT KE INDIKATOR CUACA:")
for plt_type, indikator in weather_mapping.items(): # Renamed 'plt' to 'plt_type'
    print(f"  • {plt_type} → {indikator}")

# Ambil pola cuaca dari tahun 2023 (asumsi tahun yang tersedia)
# Ini akan digunakan sebagai proxy untuk semua tahun EBT jika data cuaca tidak tersedia untuk setiap tahun EBT secara spesifik.
df_cuaca_proxy = df_cuaca[df_cuaca['Tahun'] == 2023].copy() # Assuming 2023 is the year with weather data

# Disagregasi
monthly_data = []

for _, row in df_ebt_transformed.iterrows():
    tahun = row['Tahun']
    jenis_plt = row['Jenis_PLT']
    nilai_tahunan = row['Nilai_EBT']
    kapasitas = row['Kapasitas_MW']

    # Dapatkan proporsi cuaca yang sesuai
    proporsi_col = weather_mapping.get(jenis_plt, 'Proporsi_Radiasi')

    # Gunakan data cuaca proxy (2023) untuk disagregasi
    if len(df_cuaca_proxy) > 0:
        # Disagregasi ke 12 bulan
        for _, cuaca_row in df_cuaca_proxy.iterrows(): # Use df_cuaca_proxy here
            # Pastikan proporsi_col ada di cuaca_row
            if proporsi_col in cuaca_row.index:
                proporsi = cuaca_row[proporsi_col]
                nilai_bulanan = nilai_tahunan * proporsi

                monthly_data.append({
                    'Tahun': int(tahun),
                    'Bulan': int(cuaca_row['Bulan_Num']),
                    'Bulan_Nama': cuaca_row['Bulan'],
                    'Jenis_PLT': jenis_plt,
                    'Nilai_EBT_Bulanan': nilai_bulanan,
                    'Kapasitas_MW': kapasitas,
                    'Indikator_Cuaca': proporsi_col,
                    'Proporsi': proporsi
                })
            else:
                print(f"⚠️ Peringatan: Kolom proporsi '{proporsi_col}' tidak ditemukan dalam data cuaca proxy. Baris ini akan dilewati.")

# Buat dataframe bulanan
df_monthly = pd.DataFrame(monthly_data)
df_monthly = df_monthly.sort_values(['Tahun', 'Bulan', 'Jenis_PLT']).reset_index(drop=True)

print(f"\n✓ Disagregasi selesai")
print(f"  Data tahunan: {len(df_ebt_transformed)} record")
print(f"  Data bulanan: {len(df_monthly)} record")
print(f"  Rasio: {len(df_monthly) / len(df_ebt_transformed):.0f}x")

print("\n📊 PREVIEW DATA BULANAN:")
display(df_monthly.head(15))



print("=" * 80)
print("INVERSE TRANSFORM")
print("=" * 80)

# Cek apakah ada data yang di-transform
if 'Nilai_EBT_Original' in df_ebt_transformed.columns:
    print("Data dengan log transform terdeteksi, melakukan inverse transform...\n")

    for jenis, need_transform in transform_needed.items():
        if need_transform:
            mask = df_monthly['Jenis_PLT'] == jenis
            # Inverse log transform
            df_monthly.loc[mask, 'Nilai_EBT_Bulanan'] = np.expm1(
                df_monthly.loc[mask, 'Nilai_EBT_Bulanan']
            )
            print(f"  ✓ Inverse transform untuk {jenis}")

            # POST-HOC ADJUSTMENT FOR 'PLTM' TO ENSURE SUM MATCHES ORIGINAL ANNUAL VALUE
            # This is necessary because sum(expm1(log1p(annual) * prop_i)) != annual
            for tahun_val in df_monthly.loc[mask, 'Tahun'].unique():
                original_annual_value = df_ebt[
                    (df_ebt['Tahun'] == tahun_val) &
                    (df_ebt['Jenis_PLT'] == jenis)
                ]['Nilai_EBT'].iloc[0]

                monthly_sum_current = df_monthly[
                    (df_monthly['Tahun'] == tahun_val) &
                    (df_monthly['Jenis_PLT'] == jenis)
                ]['Nilai_EBT_Bulanan'].sum()

                if monthly_sum_current > 0: # Avoid division by zero
                    scaling_factor = original_annual_value / monthly_sum_current
                    df_monthly.loc[
                        (df_monthly['Tahun'] == tahun_val) &
                        (df_monthly['Jenis_PLT'] == jenis),
                        'Nilai_EBT_Bulanan'
                    ] *= scaling_factor
                    print(f"    ✓ Post-hoc scaling diterapkan pada {jenis} tahun {tahun_val}")

    print("\n✓ Semua data telah di-inverse transform dan disesuaikan ke skala original")
else:
    print("✓ Tidak ada data yang perlu di-inverse transform")

# Pastikan tidak ada nilai negatif
df_monthly['Nilai_EBT_Bulanan'] = df_monthly['Nilai_EBT_Bulanan'].clip(lower=0)

print("\n📊 STATISTIK DATA BULANAN FINAL:")
display(df_monthly.groupby('Jenis_PLT')['Nilai_EBT_Bulanan'].describe())

print("=" * 80)
print("VALIDASI DISAGREGASI")
print("=" * 80)

# Validasi: sum bulanan harus = nilai tahunan
print("CEK: Sum 12 bulan = Nilai Tahunan?\n")

validation_results = []

for _, row in df_ebt.iterrows():
    tahun = row['Tahun']
    jenis_plt = row['Jenis_PLT']
    nilai_tahunan_original = row['Nilai_EBT']

    # Sum dari data bulanan
    monthly_sum = df_monthly[
        (df_monthly['Tahun'] == tahun) &
        (df_monthly['Jenis_PLT'] == jenis_plt)
    ]['Nilai_EBT_Bulanan'].sum()

    # Hitung selisih
    diff = abs(monthly_sum - nilai_tahunan_original)
    diff_pct = (diff / nilai_tahunan_original * 100) if nilai_tahunan_original > 0 else 0

    validation_results.append({
        'Tahun': tahun,
        'Jenis_PLT': jenis_plt,
        'Nilai_Tahunan': nilai_tahunan_original,
        'Sum_Bulanan': monthly_sum,
        'Selisih': diff,
        'Selisih_Pct': diff_pct
    })

df_validation = pd.DataFrame(validation_results)

print("HASIL VALIDASI:")
display(df_validation)

# Summary validasi
max_error = df_validation['Selisih_Pct'].max()
mean_error = df_validation['Selisih_Pct'].mean()

print(f"\n📊 STATISTIK ERROR:")
print(f"  • Error maksimum: {max_error:.4f}%")
print(f"  • Error rata-rata: {mean_error:.4f}%")

if max_error < 0.01:
    print("  ✓ VALIDASI SEMPURNA (error < 0.01%)")
elif max_error < 1:
    print("  ✓ VALIDASI BAIK (error < 1%)")
else:
    print("  ⚠️  VALIDASI PERLU DICEK (error >= 1%)")

print("=" * 80)
print("EXPORT DATASET BULANAN")
print("=" * 80)

from datetime import datetime
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# Siapkan dataset final untuk export
df_export = df_monthly[[
    'Tahun', 'Bulan', 'Bulan_Nama', 'Jenis_PLT',
    'Nilai_EBT_Bulanan', 'Kapasitas_MW', 'Indikator_Cuaca'
]].copy()

df_export = df_export.rename(columns={
    'Nilai_EBT_Bulanan': 'Produksi_EBT_GWh',
    'Kapasitas_MW': 'Kapasitas_Terpasang_MW'
})

# Export ke Excel dengan multiple sheets
excel_filename = f'EBT_Monthly_WeatherDriven_{timestamp}.xlsx'

with pd.ExcelWriter(excel_filename, engine='openpyxl') as writer:
    # Sheet 1: Data bulanan lengkap
    df_export.to_excel(writer, sheet_name='Data_Bulanan', index=False)

    # Sheet 2: Data tahunan original
    df_ebt.to_excel(writer, sheet_name='Data_Tahunan_Original', index=False)

    # Sheet 3: Data cuaca bulanan
    df_cuaca.to_excel(writer, sheet_name='Data_Cuaca_Bulanan', index=False)

print(f"✓ Data berhasil diexport ke {excel_filename}")

import matplotlib.pyplot as plt # Explicitly re-import to ensure plt is correctly defined
import seaborn as sns # Ensure seaborn is also imported if used, as it often relies on matplotlib

print("=" * 80)
print("VISUALISASI HASIL DISAGREGASI")
print("=" * 80)

# Pilih satu tahun untuk visualisasi detail
tahun_sample = df_monthly['Tahun'].iloc[0]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

jenis_list = sorted(df_monthly['Jenis_PLT'].unique())

for i, jenis in enumerate(jenis_list[:6]):
    data_jenis = df_monthly[
        (df_monthly['Jenis_PLT'] == jenis) &
        (df_monthly['Tahun'] == tahun_sample)
    ].sort_values('Bulan')

    if len(data_jenis) > 0:
        axes[i].bar(data_jenis['Bulan'], data_jenis['Nilai_EBT_Bulanan'],
                   color='steelblue', alpha=0.7)
        axes[i].set_title(f'{jenis} - Tahun {tahun_sample}', fontweight='bold')
        axes[i].set_xlabel('Bulan')
        axes[i].set_ylabel('Produksi (GWh)')
        axes[i].grid(axis='y', alpha=0.3)
        axes[i].set_xticks(range(1, 13))

# Hapus subplot kosong
for j in range(i + 1, 6):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.suptitle('Pola Produksi Bulanan per Jenis PLT (Weather Driven)',
             fontsize=14, fontweight='bold', y=1.00)
plt.show()

# Heatmap produksi bulanan
print("\n" + "=" * 80)
print("HEATMAP PRODUKSI BULANAN")

pivot_monthly = df_monthly.pivot_table(
    index='Jenis_PLT',
    columns='Bulan',
    values='Nilai_EBT_Bulanan',
    aggfunc='mean'
)

plt.figure(figsize=(14, 6))
sns.heatmap(pivot_monthly, annot=True, fmt='.2f', cmap='YlOrRd',
            linewidths=0.5, cbar_kws={'label': 'Produksi Rata-rata (GWh)'})
plt.title('Heatmap Produksi Bulanan Rata-rata per Jenis PLT',
          fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Bulan')
plt.ylabel('Jenis PLT')
plt.tight_layout()
plt.show()