# -*- coding: utf-8 -*-
"""Data_Regional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxssM-7aleuZTcvAZuZKlg4IJMqztLZG
"""

import pandas as pd
import numpy as np
import itertools
import matplotlib.pyplot as plt

RANDOM_SEED = 42          # ganti angka ini kalau ingin variasi noise yang berbeda
rng = np.random.default_rng(RANDOM_SEED)

# Upload file DATA_PHASE_3_REGIONAL_FINAL.csv ke Colab, lalu:
df = pd.read_csv('DATA_PHASE_3_REGIONAL_FINAL.csv')
df['Tanggal'] = pd.to_datetime(df['Tanggal'], format='%m/%d/%Y')
df['Tahun']  = df['Tanggal'].dt.year
df['Bulan']  = df['Tanggal'].dt.month

print(df.shape)
df.head()

def deteksi_duplikat(df):
    laporan = {}
    for j in df['Jenis'].unique():
        sub = df[df['Jenis'] == j]
        years = sorted(sub['Tahun'].unique())
        dup_pairs = []
        for y1, y2 in itertools.combinations(years, 2):
            v1 = sub[sub['Tahun'] == y1].sort_values('Bulan')['Produksi'].values
            v2 = sub[sub['Tahun'] == y2].sort_values('Bulan')['Produksi'].values
            if len(v1) == len(v2) and np.allclose(v1, v2, atol=1e-6):
                dup_pairs.append((y1, y2))
        laporan[j] = dup_pairs
    return laporan

print("=== Tahun dengan data Produksi identik persis ===")
laporan_awal = deteksi_duplikat(df)
for j, pairs in laporan_awal.items():
    if pairs:
        print(f"{j}: {pairs}")

print("\n=== Kapasitas terpasang per tahun (untuk cek anomali skala) ===")
print(df.groupby(['Jenis', 'Tahun'])['Kapasitas'].first())

CONFIG = {
    'PLT Hybrid': {'anchor': 2023, 'regenerate': [2024, 2025], 'noise_sigma': 0.05, 'growth_mean': 1.01, 'growth_sd': 0.015},
    'PLTA':       {'anchor': 2023, 'regenerate': [2024, 2025], 'noise_sigma': 0.04, 'growth_mean': 1.02, 'growth_sd': 0.02},
    'PLTB':       {'anchor': 2023, 'regenerate': [2024, 2025], 'noise_sigma': 0.06, 'growth_mean': 1.02, 'growth_sd': 0.02},
    'PLTM':       {'anchor': 2024, 'regenerate': [2025],       'noise_sigma': 0.04, 'growth_mean': 1.02, 'growth_sd': 0.015},
    'PLTMH':      {'anchor': 2023, 'regenerate': [2024, 2025], 'noise_sigma': 0.04, 'growth_mean': 1.01, 'growth_sd': 0.015},
    'PLTS':       {'anchor': 2023, 'regenerate': [2024],       'noise_sigma': 0.06, 'growth_mean': 1.02, 'growth_sd': 0.02},
}

def generate_realistic_year(template, cap_ratio, growth_mean, growth_sd,
                             noise_sigma, rng):
    """
    Menghasilkan 12 nilai produksi bulanan yang realistis berdasarkan
    template musiman tahun acuan, disesuaikan dengan:
      1. Rasio kapasitas terpasang (cap_ratio) -> efek penambahan/
         pengurangan kapasitas pembangkit.
      2. Faktor pertumbuhan organik tahunan (growth_mean/sd) -> efek
         efisiensi/jam operasi di luar kapasitas.
      3. Noise bulanan (noise_sigma) -> variabilitas operasional wajar,
         supaya pola bulan-ke-bulan tidak identik/kaku.
    """
    growth_factor = np.clip(rng.normal(growth_mean, growth_sd), 0.90, 1.20)
    noise = rng.normal(0.0, noise_sigma, size=12)
    noise = np.clip(noise, -3 * noise_sigma, 3 * noise_sigma)

    new_values = template * cap_ratio * growth_factor * (1 + noise)
    new_values = np.clip(new_values, 0, None)   # produksi tidak boleh negatif
    return new_values

df_fixed = df.copy()

for jenis, cfg in CONFIG.items():
    sub = df[df['Jenis'] == jenis]
    anchor_year = cfg['anchor']

    template   = sub[sub['Tahun'] == anchor_year].sort_values('Bulan')['Produksi'].values
    cap_anchor = sub[sub['Tahun'] == anchor_year]['Kapasitas'].iloc[0]

    for target_year in cfg['regenerate']:
        cap_target = sub[sub['Tahun'] == target_year]['Kapasitas'].iloc[0]
        cap_ratio = cap_target / cap_anchor

        new_values = generate_realistic_year(
            template=template,
            cap_ratio=cap_ratio,
            growth_mean=cfg['growth_mean'],
            growth_sd=cfg['growth_sd'],
            noise_sigma=cfg['noise_sigma'],
            rng=rng,
        )

        idx = (df_fixed[(df_fixed['Jenis'] == jenis) &
                         (df_fixed['Tahun'] == target_year)]
               .sort_values('Bulan').index)
        df_fixed.loc[idx, 'Produksi'] = new_values

print("Rekonstruksi selesai.")

print("=== Cek ulang duplikasi setelah perbaikan ===")
laporan_akhir = deteksi_duplikat(df_fixed)
for j, pairs in laporan_akhir.items():
    status = "MASIH ADA DUPLIKAT" if pairs else "OK, tidak ada duplikat"
    print(f"{j}: {status}")

print("\n=== Statistik ringkas sebelum vs sesudah (per Jenis-Tahun) ===")
ringkasan = pd.merge(
    df.groupby(['Jenis', 'Tahun'])['Produksi'].mean().rename('mean_sebelum'),
    df_fixed.groupby(['Jenis', 'Tahun'])['Produksi'].mean().rename('mean_sesudah'),
    left_index=True, right_index=True
)
print(ringkasan.round(2))

jenis_list = df['Jenis'].unique()
fig, axes = plt.subplots(len(jenis_list), 1, figsize=(9, 3 * len(jenis_list)))

for ax, jenis in zip(axes, jenis_list):
    for tahun in sorted(df[df['Jenis'] == jenis]['Tahun'].unique()):
        before = df[(df['Jenis'] == jenis) & (df['Tahun'] == tahun)].sort_values('Bulan')['Produksi'].values
        after  = df_fixed[(df_fixed['Jenis'] == jenis) & (df_fixed['Tahun'] == tahun)].sort_values('Bulan')['Produksi'].values
        ax.plot(range(1, 13), before, '--', alpha=0.4, label=f'{tahun} (sebelum)')
        ax.plot(range(1, 13), after, '-', linewidth=2, label=f'{tahun} (sesudah)')
    ax.set_title(jenis)
    ax.set_xlabel('Bulan')
    ax.set_ylabel('Produksi')
    ax.legend(fontsize=7, ncol=2)

plt.tight_layout()
plt.savefig('perbandingan_sebelum_sesudah.png', dpi=150)
plt.show()

df_final = df_fixed.drop(columns=['Tahun', 'Bulan']).copy()
df_final['Tanggal'] = df_final['Tanggal'].dt.strftime('%m/%d/%Y')

df_final.to_csv('DATA_PHASE_3_REGIONAL_MODIFIED.csv', index=False)
print("Tersimpan sebagai DATA_PHASE_3_REGIONAL_MODIFIED.csv")
df_final.head()